/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountLogin: typeof import('./src/components/login/AccountLogin.vue')['default']
    EmailLogin: typeof import('./src/components/login/EmailLogin.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PhoneLogin: typeof import('./src/components/login/PhoneLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
